/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yahtzeePackage;

/**
 *
 * @author go452180
 */
public class yahtzeeJFrame extends javax.swing.JFrame {

    /**
     * Creates new form yahtzeeJFrame
     */
    public yahtzeeJFrame() {
        initComponents();

    }
    int diceNum, diceNum2, diceNum3, diceNum4, diceNum5;
    boolean diceHold = false, diceHold2 = false, diceHold3 = false, diceHold4 = false, diceHold5 = false,oneButtonPress=false,twoButtonPress=false,threeButtonPress=false,fourButtonPress=false,fiveButtonPress=false, yahtzeeButtonPress = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dice1 = new javax.swing.JLabel();
        RollButton = new javax.swing.JButton();
        dice1Hold = new javax.swing.JButton();
        dice2 = new javax.swing.JLabel();
        dice2Hold = new javax.swing.JButton();
        dice3 = new javax.swing.JLabel();
        dice3Hold = new javax.swing.JButton();
        dice4Hold = new javax.swing.JButton();
        dice4 = new javax.swing.JLabel();
        dice5Hold = new javax.swing.JButton();
        dice5 = new javax.swing.JLabel();
        onesButton = new javax.swing.JButton();
        twosButton = new javax.swing.JButton();
        threesButton = new javax.swing.JButton();
        foursButton = new javax.swing.JButton();
        fivesButton = new javax.swing.JButton();
        sixesButton = new javax.swing.JButton();
        threeOfAKind = new javax.swing.JButton();
        sum = new javax.swing.JLabel();
        fourOfAKind = new javax.swing.JButton();
        fullHouse = new javax.swing.JButton();
        yahtzeeButton = new javax.swing.JButton();
        onesLable = new javax.swing.JLabel();
        FHLabel = new javax.swing.JLabel();
        yahtzeeLable = new javax.swing.JLabel();
        FOAKLabel = new javax.swing.JLabel();
        TOAKLable = new javax.swing.JLabel();
        sixesLable = new javax.swing.JLabel();
        fivesLable = new javax.swing.JLabel();
        foursLable = new javax.swing.JLabel();
        threesLable = new javax.swing.JLabel();
        twossButton = new javax.swing.JLabel();
        dontfour = new javax.swing.JButton();
        dontfive = new javax.swing.JButton();
        dontthree = new javax.swing.JButton();
        donttwo = new javax.swing.JButton();
        dontone = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Yahtzee");

        dice1.setText("       0");

        RollButton.setFont(new java.awt.Font("Comic Sans MS", 0, 48)); // NOI18N
        RollButton.setText("Roll!");
        RollButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RollButtonActionPerformed(evt);
            }
        });

        dice1Hold.setText("Hold");
        dice1Hold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dice1HoldActionPerformed(evt);
            }
        });

        dice2.setText("       0");

        dice2Hold.setText("Hold");
        dice2Hold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dice2HoldActionPerformed(evt);
            }
        });

        dice3.setText("       0");

        dice3Hold.setText("Hold");
        dice3Hold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dice3HoldActionPerformed(evt);
            }
        });

        dice4Hold.setText("Hold");
        dice4Hold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dice4HoldActionPerformed(evt);
            }
        });

        dice4.setText("       0");

        dice5Hold.setText("Hold");
        dice5Hold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dice5HoldActionPerformed(evt);
            }
        });

        dice5.setText("       0");

        onesButton.setText("Ones");
        onesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onesButtonActionPerformed(evt);
            }
        });

        twosButton.setText("Twos");
        twosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twosButtonActionPerformed(evt);
            }
        });

        threesButton.setText("Threes");
        threesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threesButtonActionPerformed(evt);
            }
        });

        foursButton.setText("Fours");
        foursButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foursButtonActionPerformed(evt);
            }
        });

        fivesButton.setText("Fives");
        fivesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fivesButtonActionPerformed(evt);
            }
        });

        sixesButton.setText("Sixes");

        threeOfAKind.setText("3 of a kind");
        threeOfAKind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeOfAKindActionPerformed(evt);
            }
        });

        sum.setText("       Sum");
        sum.setOpaque(true);

        fourOfAKind.setText("4 of a kind");

        fullHouse.setText("Full House");

        yahtzeeButton.setText("Yahtzee");
        yahtzeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yahtzeeButtonActionPerformed(evt);
            }
        });

        onesLable.setBackground(new java.awt.Color(255, 102, 102));
        onesLable.setOpaque(true);

        FHLabel.setBackground(new java.awt.Color(255, 102, 102));
        FHLabel.setOpaque(true);

        yahtzeeLable.setBackground(new java.awt.Color(255, 102, 102));
        yahtzeeLable.setOpaque(true);

        FOAKLabel.setBackground(new java.awt.Color(255, 102, 102));
        FOAKLabel.setOpaque(true);

        TOAKLable.setBackground(new java.awt.Color(255, 102, 102));
        TOAKLable.setOpaque(true);

        sixesLable.setBackground(new java.awt.Color(255, 102, 102));
        sixesLable.setOpaque(true);

        fivesLable.setBackground(new java.awt.Color(255, 102, 102));
        fivesLable.setOpaque(true);

        foursLable.setBackground(new java.awt.Color(255, 102, 102));
        foursLable.setOpaque(true);

        threesLable.setBackground(new java.awt.Color(255, 102, 102));
        threesLable.setOpaque(true);

        twossButton.setBackground(new java.awt.Color(255, 102, 102));
        twossButton.setOpaque(true);

        dontfour.setText("Don't");

        dontfive.setText("Don't");

        dontthree.setText("Don't");

        donttwo.setText("Don't");
        donttwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donttwoActionPerformed(evt);
            }
        });

        dontone.setText("Don't");
        dontone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dontoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(twossButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(136, 136, 136)
                                        .addComponent(jLabel1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(dice1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(dice1Hold, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(dice2Hold))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addComponent(dice2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(6, 6, 6)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(dice3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(dice3Hold)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(dontone)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(donttwo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(dontthree)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(13, 13, 13)
                                                .addComponent(dice4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(dontfour)
                                                    .addComponent(dice4Hold))
                                                .addGap(4, 4, 4)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dice5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dontfive)
                                    .addComponent(dice5Hold))
                                .addGap(42, 42, 42))
                            .addComponent(RollButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(threesLable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                    .addComponent(foursLable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fivesLable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sixesLable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TOAKLable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(FOAKLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(FHLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(yahtzeeLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(onesLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(sum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sixesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fivesButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(onesButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(twosButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(threesButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(foursButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(threeOfAKind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fourOfAKind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fullHouse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(yahtzeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RollButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(49, 49, 49))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(onesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(onesLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(twosButton)
                            .addComponent(twossButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(threesLable, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dice1)
                        .addComponent(dice2)
                        .addComponent(dice3)
                        .addComponent(dice4)
                        .addComponent(dice5)
                        .addComponent(threesButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dice1Hold)
                        .addComponent(dice2Hold)
                        .addComponent(dice3Hold)
                        .addComponent(dice4Hold)
                        .addComponent(dice5Hold)
                        .addComponent(foursButton))
                    .addComponent(foursLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(fivesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fivesLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dontfour)
                        .addComponent(dontfive)
                        .addComponent(dontthree)
                        .addComponent(donttwo)
                        .addComponent(dontone)))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sixesButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sum, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sixesLable, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(threeOfAKind)
                    .addComponent(TOAKLable, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fourOfAKind)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fullHouse))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(FOAKLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FHLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yahtzeeLable, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yahtzeeButton))
                .addGap(93, 93, 93))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dice2HoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dice2HoldActionPerformed
       diceHold2 = true;
        donttwo.setEnabled(true);
        dice2Hold.setEnabled(false);
    }//GEN-LAST:event_dice2HoldActionPerformed

    private void dice4HoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dice4HoldActionPerformed
        diceHold4 = true;
        dontfour.setEnabled(true);
        dice4Hold.setEnabled(false);
    }//GEN-LAST:event_dice4HoldActionPerformed

    private void RollButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RollButtonActionPerformed
        String holdDice = null, holdDice2 = null, holdDice3 = null, holdDice4 = null, holdDice5 = null;
       

        if (diceHold == false) {
            diceNum = (int) Math.round(Math.random() * 5 + 1);
            holdDice = Integer.toString(diceNum);
            dice1.setText(holdDice);
        }

        if (diceHold2 == false) {
            diceNum2 = (int) Math.round(Math.random() * 5 + 1);
            holdDice2 = Integer.toString(diceNum2);
            dice2.setText(holdDice2);

        }

        if (diceHold3 == false) {
            diceNum3 = (int) Math.round(Math.random() * 5 + 1);
            holdDice3 = Integer.toString(diceNum3);
            dice3.setText(holdDice3);
        }
        if (diceHold4 == false) {
            diceNum4 = (int) Math.round(Math.random() * 5 + 1);
            holdDice4 = Integer.toString(diceNum4);
            dice4.setText(holdDice4);

        }
        if (diceHold5 == false) {
            diceNum5 = (int) Math.round(Math.random() * 5 + 1);
            holdDice5 = Integer.toString(diceNum5);
            dice5.setText(holdDice5);

        }
        //ones
        if (diceNum == 1 || diceNum2 == 1 || diceNum3 == 1 || diceNum4 == 1 || diceNum5 == 1) {
            onesLable.setText(Integer.toString(diceNum + diceNum2 + diceNum3 + diceNum4 + diceNum5));

            

        } else {
            onesLable.setText(" ");
        }
        //twos
        if (diceNum == 2 || diceNum2 == 2 || diceNum3 == 2 || diceNum4 == 2 || diceNum5 == 2) {
            twossButton.setText(Integer.toString(diceNum + diceNum2 + diceNum3 + diceNum4 + diceNum5));

        } else {
            twossButton.setText(" ");
        }
        //threes
        if (diceNum == 3 || diceNum2 == 3 || diceNum3 == 3 || diceNum4 == 3 || diceNum5 == 3) {
            threesLable.setText(Integer.toString(diceNum + diceNum2 + diceNum3 + diceNum4 + diceNum5));

        } else {

            threesLable.setText(" ");
        }
        //fours
        if (diceNum == 4 || diceNum2 == 4 || diceNum3 == 4 || diceNum4 == 4 || diceNum5 == 4) {
            foursLable.setText(Integer.toString(diceNum + diceNum2 + diceNum3 + diceNum4 + diceNum5));

        } else {

            foursLable.setText(" ");
        }
        //fives
        if (diceNum == 5 || diceNum2 == 5 || diceNum3 == 5 || diceNum4 == 5 || diceNum5 == 5) {
            fivesLable.setText(Integer.toString(diceNum + diceNum2 + diceNum3 + diceNum4 + diceNum5));

        } else {

            fivesLable.setText(" ");
        }
        //sixes
        if (diceNum == 6 || diceNum2 == 6 || diceNum3 == 6 || diceNum4 == 6 || diceNum5 == 6) {
            sixesLable.setText(Integer.toString(diceNum + diceNum2 + diceNum3 + diceNum4 + diceNum5));

        } else {

            sixesLable.setText(" ");
        }
        //yahtzee
        if(yahtzeeButtonPress==false){
            if (diceNum == diceNum2 && diceNum2 == diceNum3 && diceNum3 == diceNum4 && diceNum4 == diceNum5) {
                yahtzeeLable.setText(Integer.toString(diceNum + diceNum2 + diceNum3 + diceNum4 + diceNum5));
                yahtzeeButton.setEnabled(true);
                System.out.println("working");
            } else {
                yahtzeeButton.setEnabled(false);
                yahtzeeLable.setText(" ");

            }
        } 

    }//GEN-LAST:event_RollButtonActionPerformed

    private void dice1HoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dice1HoldActionPerformed
        diceHold = true;
        dontone.setEnabled(true);
        dice1Hold.setEnabled(false);
    }//GEN-LAST:event_dice1HoldActionPerformed

    private void dice3HoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dice3HoldActionPerformed
        diceHold3 = true;
        dontthree.setEnabled(true);
        dice3Hold.setEnabled(false);
    }//GEN-LAST:event_dice3HoldActionPerformed

    private void dice5HoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dice5HoldActionPerformed
        diceHold5 = true;
        dontfive.setEnabled(true);
        dice5Hold.setEnabled(false);
    }//GEN-LAST:event_dice5HoldActionPerformed

    private void onesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onesButtonActionPerformed
        onesButton.setEnabled(false);
        diceHold = false;
        dontone.setEnabled(false);
        dice1Hold.setEnabled(true);
        diceHold2 = false;
        donttwo.setEnabled(false);
        dice2Hold.setEnabled(true);
        diceHold3 = false;
        dontthree.setEnabled(false);
        dice3Hold.setEnabled(true);
        diceHold4 = false;
        dontfour.setEnabled(false);
        dice4Hold.setEnabled(true);
        diceHold5 = false;
        dontfive.setEnabled(false);
        dice5Hold.setEnabled(true);
        oneButtonPress = true;
    }//GEN-LAST:event_onesButtonActionPerformed

    private void threeOfAKindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeOfAKindActionPerformed
       yahtzeeButtonPress = true;
    }//GEN-LAST:event_threeOfAKindActionPerformed

    private void yahtzeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yahtzeeButtonActionPerformed
        yahtzeeButton.setEnabled(false);
        diceHold = false;
        dontone.setEnabled(false);
        dice1Hold.setEnabled(true);
        diceHold2 = false;
        donttwo.setEnabled(false);
        dice2Hold.setEnabled(true);
        diceHold3 = false;
        dontthree.setEnabled(false);
        dice3Hold.setEnabled(true);
        diceHold4 = false;
        dontfour.setEnabled(false);
        dice4Hold.setEnabled(true);
        diceHold5 = false;
        dontfive.setEnabled(false);
        dice5Hold.setEnabled(true);
        yahtzeeButtonPress=true;
    }//GEN-LAST:event_yahtzeeButtonActionPerformed

    private void dontoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dontoneActionPerformed
        diceHold = false;
        dontone.setEnabled(false);
        dice1Hold.setEnabled(true);
    }//GEN-LAST:event_dontoneActionPerformed

    private void donttwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donttwoActionPerformed
        diceHold2 = false;
        donttwo.setEnabled(false);
        dice2Hold.setEnabled(true);
    }//GEN-LAST:event_donttwoActionPerformed

    private void twosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twosButtonActionPerformed
       twosButton.setEnabled(false);
        diceHold = false;
        dontone.setEnabled(false);
        dice1Hold.setEnabled(true);
        diceHold2 = false;
        donttwo.setEnabled(false);
        dice2Hold.setEnabled(true);
        diceHold3 = false;
        dontthree.setEnabled(false);
        dice3Hold.setEnabled(true);
        diceHold4 = false;
        dontfour.setEnabled(false);
        dice4Hold.setEnabled(true);
        diceHold5 = false;
        dontfive.setEnabled(false);
        dice5Hold.setEnabled(true);
        twoButtonPress = true;
    }//GEN-LAST:event_twosButtonActionPerformed

    private void threesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threesButtonActionPerformed
        threesButton.setEnabled(false);
        diceHold = false;
        dontone.setEnabled(false);
        dice1Hold.setEnabled(true);
        diceHold2 = false;
        donttwo.setEnabled(false);
        dice2Hold.setEnabled(true);
        diceHold3 = false;
        dontthree.setEnabled(false);
        dice3Hold.setEnabled(true);
        diceHold4 = false;
        dontfour.setEnabled(false);
        dice4Hold.setEnabled(true);
        diceHold5 = false;
        dontfive.setEnabled(false);
        dice5Hold.setEnabled(true);
        threeButtonPress = true;
    }//GEN-LAST:event_threesButtonActionPerformed

    private void foursButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foursButtonActionPerformed
foursButton.setEnabled(false);
        diceHold = false;
        dontone.setEnabled(false);
        dice1Hold.setEnabled(true);
        diceHold2 = false;
        donttwo.setEnabled(false);
        dice2Hold.setEnabled(true);
        diceHold3 = false;
        dontthree.setEnabled(false);
        dice3Hold.setEnabled(true);
        diceHold4 = false;
        dontfour.setEnabled(false);
        dice4Hold.setEnabled(true);
        diceHold5 = false;
        dontfive.setEnabled(false);
        dice5Hold.setEnabled(true);
        fourButtonPress = true;        
    }//GEN-LAST:event_foursButtonActionPerformed

    private void fivesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fivesButtonActionPerformed
        fivesButton.setEnabled(false);
        diceHold = false;
        dontone.setEnabled(false);
        dice1Hold.setEnabled(true);
        diceHold2 = false;
        donttwo.setEnabled(false);
        dice2Hold.setEnabled(true);
        diceHold3 = false;
        dontthree.setEnabled(false);
        dice3Hold.setEnabled(true);
        diceHold4 = false;
        dontfour.setEnabled(false);
        dice4Hold.setEnabled(true);
        diceHold5 = false;
        dontfive.setEnabled(false);
        dice5Hold.setEnabled(true);
        fiveButtonPress = true;
    }//GEN-LAST:event_fivesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(yahtzeeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(yahtzeeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(yahtzeeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(yahtzeeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new yahtzeeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FHLabel;
    private javax.swing.JLabel FOAKLabel;
    private javax.swing.JButton RollButton;
    private javax.swing.JLabel TOAKLable;
    private javax.swing.JLabel dice1;
    private javax.swing.JButton dice1Hold;
    private javax.swing.JLabel dice2;
    private javax.swing.JButton dice2Hold;
    private javax.swing.JLabel dice3;
    private javax.swing.JButton dice3Hold;
    private javax.swing.JLabel dice4;
    private javax.swing.JButton dice4Hold;
    private javax.swing.JLabel dice5;
    private javax.swing.JButton dice5Hold;
    private javax.swing.JButton dontfive;
    private javax.swing.JButton dontfour;
    private javax.swing.JButton dontone;
    private javax.swing.JButton dontthree;
    private javax.swing.JButton donttwo;
    private javax.swing.JButton fivesButton;
    private javax.swing.JLabel fivesLable;
    private javax.swing.JButton fourOfAKind;
    private javax.swing.JButton foursButton;
    private javax.swing.JLabel foursLable;
    private javax.swing.JButton fullHouse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton onesButton;
    private javax.swing.JLabel onesLable;
    private javax.swing.JButton sixesButton;
    private javax.swing.JLabel sixesLable;
    private javax.swing.JLabel sum;
    private javax.swing.JButton threeOfAKind;
    private javax.swing.JButton threesButton;
    private javax.swing.JLabel threesLable;
    private javax.swing.JButton twosButton;
    private javax.swing.JLabel twossButton;
    private javax.swing.JButton yahtzeeButton;
    private javax.swing.JLabel yahtzeeLable;
    // End of variables declaration//GEN-END:variables
}
